benches/vart_bench.rs, src/art.rs, src/iter.rs, src/lib.rs, src/node.rs, src/snapshot.rs
This PR ports changes from surrealkv index into vart. It makes the following changes
- Remove usage of assert during key creation
- Change VariableKey to VariableSizeKey
- Change FixedKey to FixedSizeKey
=> Avoid unwrap during key creation

Cargo.lock, Cargo.toml, src/art.rs, src/iter.rs, src/lib.rs, src/snapshot.rs
The idea to keep track of active snapshots was to control the number of snapshots spawned in case we write snapshots to file. There is no need to keep track of snapshots currently as it provides no real benefit, and there are no writes to disk for vart right now.
=> chore: remove snapshot counters

src/art.rs, src/node.rs
Insertion into the Flatnode were falsely sorting the key in reverse order. This lead to unsorted keys in flatnodes
=> fix: sorting in flatnode

src/art.rs, src/lib.rs, src/snapshot.rs
This pull request (PR) addresses two critical issues:
- **Issue:** The `remove` method previously had a significant bug where it would remove all children matching a particular prefix without considering the type of the child node.
- **Fix:** The method has been updated to include a check on the type of child node before performing the removal. This ensures that only the intended nodes are removed, maintaining the integrity of the tree structure.
- **Issue:** The `insert` method did not check if the node type was full before attempting to add children. This could lead to failures when the tree is shrunk to the last key and a new key is inserted without prior growth.
- **Fix:** The method now first checks if the node type is full. If it is, the node is grown accordingly before adding any …
=> Fix insert and remove method

src/art.rs, src/node.rs
`KeyTrait` is already defined with the `Clone` trait bound.
=> Remove unnecessary Clone trait bounds

src/art.rs, src/iter.rs, src/node.rs, src/snapshot.rs
This PR does the following
1) Adds the following versioned APIs to the snapshot and tree
- `get_at_ts` (to get a key at a particular timestamp)
- `get_all_versions` (to get all the versions of a key)
- `scan_at_ts` (scans all keys at a timestamp)
- `keys_at_ts` (query all keys at a timestamp)
2) Avoid returning the key from all the get APIs
3) Shorten function name `insert_without_version_increment_check` ---> `insert_unchecked`
4) Fix an issue with duplicate insertion (two keys with the same version) into the twig node, where the duplicate node is not sorted by timestamp
5) Add `get_value_by_query` to both tree and snapshot to query the value by the following query types
- `LatestByVersion`
- `LatestByTs`
- `LastLessThanTs`
- `LastLessOrEqualTs`
- `FirstGreaterThanTs`
- …
=> chore: add versioned apis

src/art.rs, src/lib.rs, src/snapshot.rs
- From the ergonomics perspective, it's better if `get` methods return `Option` instead of `Result`.
- The previous change also makes it possible to remove all of the `TrieError` variants except `FixedSizeKeyLengthExceeded` needed for the fallible conversions.
- Convert two occurrences of `TrieError::Other()` into a proper `TrieError::VersionIsOld` variant.
For the future, we should probably take care of the conversion methods from strings and slices for fixed size keys, and make them consistently return `Result<..., TrieError::FixedSizeKeyLengthExceeded>` instead of (debug) asserts.
=> make get methods return Option instead of Result

src/art.rs, src/lib.rs
- Make `Key::prefix_after()` return a slice of the original key without any allocation and copying.
- Do the same for `Key:: prefix_before()` for consistency. It's used only in one place, so there's no harm in one extra `.into()`.
- Unrelated, but also simplify `KeyTrait` and its blanket impl by removing unnecessary trait bounds.
In most cases `prefix = key.prefix_after()` is immediately followed by `prefix.as_slice()`, suggesting that there is no need to allocate the intermediate key just to convert it to a slice on the next line. This change improves the performance of gets as shown in the `cargo bench` output below:
=> Return prefixes as slices instead of vectors

.github/workflows/ci.yml, src/art.rs, src/iter.rs, src/node.rs, src/snapshot.rs
This PR modifies the iterator to satisfy the DoubleEndedIterator trait to allow for reverse lookups.
=> chore: add double ended iterator

Cargo.lock, Cargo.toml, src/art.rs, src/iter.rs
Range scans are extremely slow because there is no check whilst iterating to see if the prefix falls within the specified range bound. Currently, for any range scan, the entire set of keys are read, which makes it extremely slow. This PR attempts to fixe it by introducing bound checks during the DFS on range scan.
=> Fix: range scans

src/art.rs
Removes unused variable `new_version` in bulk_insert
=> chore: remove unused variable new_version in bulk_insert

src/art.rs, src/snapshot.rs
Each insert operation currently fetches the old record from the twig node to present the old value, which is not used in SurrealKV or elsewhere. This PR eliminates this check, which can lead to performance improvements if there are multiple versions on the twig node.
=> perf: remove old value lookup on insert

Cargo.lock, Cargo.toml, src/art.rs
Relax little bit the versioned guarantees of `Tree::insert` by allowing values with the versions equal to the root. This allows us to remove `Tree::bulk_insert`, because now the normal `Tree::insert` can be used in the most common path in SurrealKV when writing committed entries.
Tested with SurrealKV and SurrealDB.
=> Remove bulk insert and allow inserting equal versions

benches/vart_bench.rs, src/iter.rs
This PR adds method inlining for the next method in Iter/Range methods. Also adds benchmark to measure the improvements.
without inlining
```
iter_benchmark/art/1000000
time:   [25.493 ms 25.539 ms 25.588 ms]
thrpt:  [39.081  elem/s 39.156  elem/s 39.226  elem/s]
range_benchmark/art/1000000
time:   [32.368 ms 32.672 ms 33.110 ms]
thrpt:  [30.202  elem/s 30.608  elem/s 30.895  elem/s]
```
with inlining
```
iter_benchmark/art/1000000
time:   [5.5269 ms 5.8293 ms 6.3694 ms]
thrpt:  [157.00  elem/s 171.55  elem/s 180.93  elem/s]
change:
time:   [-78.351% -77.175% -75.171%] (p = 0.00 < 0.05)
thrpt:  [+302.76% +338.12% +361.92%]
Performance has improved.
range_benchmark/art/1000000
time:   [11.827 ms 12.020 ms 12.324 ms]
thrpt:  [81.140  elem/s 83.197  elem/s 84.550  elem/s]
change:
time: …
```
=> perf: add inlining for range/iter and benchmark

src/art.rs, src/node.rs
Instead of cloning the current node, then growing it if more space is needed with another allocation, and then adding a child with one more allocation, we can either grow or clone the node right away and then mutably add new child to it.
Tested with SurrealKV and SurrealDB.
=> Reduce allocations in Node::add_child

benches/vart_bench.rs, src/art.rs, src/lib.rs, src/node.rs
`insert_unchecked` is a method used in surrealkv to load the index on startup. Currently, the load times are extremely slow because insertion at start incurs the CoW (copy-on-write) penalty unnecessarily, which is only required during transactions.
This PR makes the method mutable, so that it avoids CoW.
=> perf: make insert_unchecked mutable to avoid cow

src/art.rs, src/iter.rs, src/node.rs
As per the ART paper, when a Node4 has a single child should have its child collapsed into it. Currently this is not implemented, and rather a Node4 is collapsed into a Node1 which doesn't really help in compression. This PR implements delete as per the paper.
Some benchmark results
```
seq_delete/vart         time:   [1.3538 µs 1.3743 µs 1.3913 µs]
thrpt:  [718.76 Kelem/s 727.64 Kelem/s 738.67 Kelem/s]
rand_delete/vart        time:   [2.4015 µs 2.4515 µs 2.5083 µs]
thrpt:  [398.68 Kelem/s 407.92 Kelem/s 416.40 Kelem/s]
```
```
seq_delete/vart         time:   [1.1587 µs 1.1767 µs 1.1914 µs]
thrpt:  [839.36 Kelem/s 849.85 Kelem/s 863.07 Kelem/s]
rand_delete/vart        time:   [1.8899 µs 1.9467 µs 2.0162 µs]
thrpt:  [495.99 Kelem/s 513.70 Kelem/s 529.12 Kelem/s]
```
=> chore: collapse node4 to child and get rid of node 1

Cargo.lock, Cargo.toml, src/art.rs, src/node.rs, src/snapshot.rs
Add `Tree::insert_or_replace` and `Tree::insert_or_replace_unchecked` methods. They will be used in SurrealKV configured to run without versions. The idea is that since we don't need to keep previous versions of values in the index in memory, then for the existing keys we can simply replace the previous value with the new one by using `Tree::insert_or_replace`. `Tree::insert_or_replace_unchecked` is used for loading the index, so we only keep the value with the largest version, i.e. the most recent one.
A few notes:
1. The implementation is simple but not the most optimised one. In the future we might want to add a special method for `Twig` nodes instead of clearing all existing values and then doing `insert_mut()`.
2. This implementation is not sufficient for handling the online …
=> Add insert_or_replace methods

src/art.rs
Tested with SurrealKV and SurrealDB.
=> Do not clone prefix when inserting

Cargo.lock, Cargo.toml, src/art.rs, src/lib.rs, src/snapshot.rs
This PR allows creating a snapshot at a specified version. Also bumps the version for release
=> chore: allow creating custom snapshot

benches/vart_bench.rs, src/art.rs, src/node.rs
Inserts are extremely slow because on every insert the version has to be updated across all the higher nodes which is not really necessary.
main:
```
seq_insert/vart         time:   [1.0669 µs 1.0857 µs 1.1037 µs]
thrpt:  [906.07 Kelem/s 921.08 Kelem/s 937.26 Kelem/s]
seq_insert_mut/vart     time:   [298.19 ns 304.07 ns 313.97 ns]
thrpt:  [3.1850 Melem/s 3.2888 Melem/s 3.3536 Melem/s]
rand_insert/vart        time:   [1.2074 µs 1.2355 µs 1.2623 µs]
thrpt:  [792.20 Kelem/s 809.38 Kelem/s 828.26 Kelem/s]
rand_insert_mut/vart    time:   [435.92 ns 447.12 ns 460.86 ns]
thrpt:  [2.1699 Melem/s 2.2365 Melem/s 2.2940 Melem/s]
seq_delete/vart         time:   [1.1476 µs 1.1649 µs 1.1792 µs]
thrpt:  [848.06 Kelem/s 858.41 Kelem/s 871.36 Kelem/s]
rand_delete/vart        time:   [897.98 ns 944.47 ns …
```
=> Perf: remove version from nodes

.github/workflows/ci.yml, .github/workflows/release.yml
This PR implements an automated release process. The workflow is triggered by pull requests targeting branches matching the release/* pattern.
1. **Extract Version**: The version is extracted from the branch name (formatted as release/{version}) and validated against the version specified in Cargo.toml. If they do not match, the workflow fails.
2. **Check Semver**: The workflow includes a step to check if the versioning adheres to semantic versioning standards.
3. **Create and Push Tag**: A tag is created for the release version, and it is pushed to the origin repository.
4. **Generate Changelog**: A changelog is generated using the git-cliff-action, providing a summary of changes since the last release.
5. **Commit Changelog**: If the changelog has changes, it is committed and pushed to …
=> chore: add release ci

src/art.rs, src/iter.rs, src/node.rs
Since key is not used anywhere it can actually be removed from the vart iterator object.
Tested with SurrealKV and SurrealDB.
=> Iterator only needs a node reference

src/art.rs, src/iter.rs
This PR removes `keys_at_ts` function because scan_at_ts iterator can be reused to filter out for only keys. This avoids having repeated code for the same functionality
=> remove: keys_at_ts
